DROP DATABASE IF EXISTS carparkDB;
CREATE SCHEMA IF NOT EXISTS carparkDB;
use carparkDB;
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    contact_number BIGINT(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);